<?php
/**
 * ShipmentManifestingRequest
 *
 * PHP version 8.1
 *
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.12
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\DHL\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use kruegge82\DHL\ObjectSerializer;

/**
 * ShipmentManifestingRequest Class Doc Comment
 *
 * @description List of shipments which shall be manifested.
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ShipmentManifestingRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ShipmentManifestingRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'profile' => 'string',
        'shipment_numbers' => 'string[]',
        'billing_number' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'profile' => null,
        'shipment_numbers' => null,
        'billing_number' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'profile' => false,
        'shipment_numbers' => false,
        'billing_number' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'profile' => 'profile',
        'shipment_numbers' => 'shipmentNumbers',
        'billing_number' => 'billingNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'profile' => 'setProfile',
        'shipment_numbers' => 'setShipmentNumbers',
        'billing_number' => 'setBillingNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'profile' => 'getProfile',
        'shipment_numbers' => 'getShipmentNumbers',
        'billing_number' => 'getBillingNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('profile', $data ?? [], null);
        $this->setIfExists('shipment_numbers', $data ?? [], null);
        $this->setIfExists('billing_number', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['profile'] === null) {
            $invalidProperties[] = "'profile' can't be null";
        }
        if ((mb_strlen($this->container['profile']) > 35)) {
            $invalidProperties[] = "invalid value for 'profile', the character length must be smaller than or equal to 35.";
        }

        if ((mb_strlen($this->container['profile']) < 0)) {
            $invalidProperties[] = "invalid value for 'profile', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['shipment_numbers']) && (count($this->container['shipment_numbers']) > 30)) {
            $invalidProperties[] = "invalid value for 'shipment_numbers', number of items must be less than or equal to 30.";
        }

        if (!is_null($this->container['shipment_numbers']) && (count($this->container['shipment_numbers']) < 1)) {
            $invalidProperties[] = "invalid value for 'shipment_numbers', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets profile
     *
     * @return string
     */
    public function getProfile(): string
    {
        return $this->container['profile'];
    }

    /**
     * Sets profile
     *
     * @param string $profile profile
     *
     * @return $this
     */
    public function setProfile(string $profile): static
    {
        if (is_null($profile)) {
            throw new InvalidArgumentException('non-nullable profile cannot be null');
        }
        if ((mb_strlen($profile) > 35)) {
            throw new InvalidArgumentException('invalid length for $profile when calling ShipmentManifestingRequest., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($profile) < 0)) {
            throw new InvalidArgumentException('invalid length for $profile when calling ShipmentManifestingRequest., must be bigger than or equal to 0.');
        }

        $this->container['profile'] = $profile;

        return $this;
    }

    /**
     * Gets shipment_numbers
     *
     * @return string[]|null
     */
    public function getShipmentNumbers(): ?array
    {
        return $this->container['shipment_numbers'];
    }

    /**
     * Sets shipment_numbers
     *
     * @param string[]|null $shipment_numbers List of shipment IDs for manifesting.
     *
     * @return $this
     */
    public function setShipmentNumbers(?array $shipment_numbers): static
    {
        if (is_null($shipment_numbers)) {
            throw new InvalidArgumentException('non-nullable shipment_numbers cannot be null');
        }

        if ((count($shipment_numbers) > 30)) {
            throw new InvalidArgumentException('invalid value for $shipment_numbers when calling ShipmentManifestingRequest., number of items must be less than or equal to 30.');
        }
        if ((count($shipment_numbers) < 1)) {
            throw new InvalidArgumentException('invalid length for $shipment_numbers when calling ShipmentManifestingRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['shipment_numbers'] = $shipment_numbers;

        return $this;
    }

    /**
     * Gets billing_number
     *
     * @return string|null
     */
    public function getBillingNumber(): ?string
    {
        return $this->container['billing_number'];
    }

    /**
     * Sets billing_number
     *
     * @param string|null $billing_number Customer billingNumber number.
     *
     * @return $this
     */
    public function setBillingNumber(?string $billing_number): static
    {
        if (is_null($billing_number)) {
            throw new InvalidArgumentException('non-nullable billing_number cannot be null');
        }
        $this->container['billing_number'] = $billing_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


