<?php
/**
 * VASCashOnDelivery
 *
 * PHP version 8.1
 *
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.12
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\DHL\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use kruegge82\DHL\ObjectSerializer;

/**
 * VASCashOnDelivery Class Doc Comment
 *
 * @description Cash on delivery (Nachnahme). Currency must be Euro. Either bank account information or account reference (from customer profile) must be provided. Transfernote1 + 2 are references transmitted during bank transfer. Providing account information explicitly requires elevated privileges.
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class VASCashOnDelivery implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'VASCashOnDelivery';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'amount' => '\kruegge82\DHL\Model\Value',
        'bank_account' => '\kruegge82\DHL\Model\BankAccount',
        'account_reference' => 'string',
        'transfer_note1' => 'string',
        'transfer_note2' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'amount' => null,
        'bank_account' => null,
        'account_reference' => null,
        'transfer_note1' => null,
        'transfer_note2' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'amount' => false,
        'bank_account' => false,
        'account_reference' => false,
        'transfer_note1' => false,
        'transfer_note2' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'amount' => 'amount',
        'bank_account' => 'bankAccount',
        'account_reference' => 'accountReference',
        'transfer_note1' => 'transferNote1',
        'transfer_note2' => 'transferNote2'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'amount' => 'setAmount',
        'bank_account' => 'setBankAccount',
        'account_reference' => 'setAccountReference',
        'transfer_note1' => 'setTransferNote1',
        'transfer_note2' => 'setTransferNote2'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'amount' => 'getAmount',
        'bank_account' => 'getBankAccount',
        'account_reference' => 'getAccountReference',
        'transfer_note1' => 'getTransferNote1',
        'transfer_note2' => 'getTransferNote2'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('bank_account', $data ?? [], null);
        $this->setIfExists('account_reference', $data ?? [], null);
        $this->setIfExists('transfer_note1', $data ?? [], null);
        $this->setIfExists('transfer_note2', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['account_reference']) && (mb_strlen($this->container['account_reference']) > 35)) {
            $invalidProperties[] = "invalid value for 'account_reference', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['account_reference']) && (mb_strlen($this->container['account_reference']) < 0)) {
            $invalidProperties[] = "invalid value for 'account_reference', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['transfer_note1']) && (mb_strlen($this->container['transfer_note1']) > 35)) {
            $invalidProperties[] = "invalid value for 'transfer_note1', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['transfer_note1']) && (mb_strlen($this->container['transfer_note1']) < 0)) {
            $invalidProperties[] = "invalid value for 'transfer_note1', the character length must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['transfer_note2']) && (mb_strlen($this->container['transfer_note2']) > 35)) {
            $invalidProperties[] = "invalid value for 'transfer_note2', the character length must be smaller than or equal to 35.";
        }

        if (!is_null($this->container['transfer_note2']) && (mb_strlen($this->container['transfer_note2']) < 0)) {
            $invalidProperties[] = "invalid value for 'transfer_note2', the character length must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets amount
     *
     * @return \kruegge82\DHL\Model\Value|null
     */
    public function getAmount(): ?\kruegge82\DHL\Model\Value
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param \kruegge82\DHL\Model\Value|null $amount amount
     *
     * @return $this
     */
    public function setAmount(?\kruegge82\DHL\Model\Value $amount): static
    {
        if (is_null($amount)) {
            throw new InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets bank_account
     *
     * @return \kruegge82\DHL\Model\BankAccount|null
     */
    public function getBankAccount(): ?\kruegge82\DHL\Model\BankAccount
    {
        return $this->container['bank_account'];
    }

    /**
     * Sets bank_account
     *
     * @param \kruegge82\DHL\Model\BankAccount|null $bank_account bank_account
     *
     * @return $this
     */
    public function setBankAccount(?\kruegge82\DHL\Model\BankAccount $bank_account): static
    {
        if (is_null($bank_account)) {
            throw new InvalidArgumentException('non-nullable bank_account cannot be null');
        }
        $this->container['bank_account'] = $bank_account;

        return $this;
    }

    /**
     * Gets account_reference
     *
     * @return string|null
     */
    public function getAccountReference(): ?string
    {
        return $this->container['account_reference'];
    }

    /**
     * Sets account_reference
     *
     * @param string|null $account_reference Reference to bank account details. Account references are maintained in customer settings in Post & DHL business customer portal under Ship -> Settings -> Cash on delivery. Please note, that the default account reference is used if the provided account reference does not exist in your customer settings!
     *
     * @return $this
     */
    public function setAccountReference(?string $account_reference): static
    {
        if (is_null($account_reference)) {
            throw new InvalidArgumentException('non-nullable account_reference cannot be null');
        }
        if ((mb_strlen($account_reference) > 35)) {
            throw new InvalidArgumentException('invalid length for $account_reference when calling VASCashOnDelivery., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($account_reference) < 0)) {
            throw new InvalidArgumentException('invalid length for $account_reference when calling VASCashOnDelivery., must be bigger than or equal to 0.');
        }

        $this->container['account_reference'] = $account_reference;

        return $this;
    }

    /**
     * Gets transfer_note1
     *
     * @return string|null
     */
    public function getTransferNote1(): ?string
    {
        return $this->container['transfer_note1'];
    }

    /**
     * Sets transfer_note1
     *
     * @param string|null $transfer_note1 transfer_note1
     *
     * @return $this
     */
    public function setTransferNote1(?string $transfer_note1): static
    {
        if (is_null($transfer_note1)) {
            throw new InvalidArgumentException('non-nullable transfer_note1 cannot be null');
        }
        if ((mb_strlen($transfer_note1) > 35)) {
            throw new InvalidArgumentException('invalid length for $transfer_note1 when calling VASCashOnDelivery., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($transfer_note1) < 0)) {
            throw new InvalidArgumentException('invalid length for $transfer_note1 when calling VASCashOnDelivery., must be bigger than or equal to 0.');
        }

        $this->container['transfer_note1'] = $transfer_note1;

        return $this;
    }

    /**
     * Gets transfer_note2
     *
     * @return string|null
     */
    public function getTransferNote2(): ?string
    {
        return $this->container['transfer_note2'];
    }

    /**
     * Sets transfer_note2
     *
     * @param string|null $transfer_note2 transfer_note2
     *
     * @return $this
     */
    public function setTransferNote2(?string $transfer_note2): static
    {
        if (is_null($transfer_note2)) {
            throw new InvalidArgumentException('non-nullable transfer_note2 cannot be null');
        }
        if ((mb_strlen($transfer_note2) > 35)) {
            throw new InvalidArgumentException('invalid length for $transfer_note2 when calling VASCashOnDelivery., must be smaller than or equal to 35.');
        }
        if ((mb_strlen($transfer_note2) < 0)) {
            throw new InvalidArgumentException('invalid length for $transfer_note2 when calling VASCashOnDelivery., must be bigger than or equal to 0.');
        }

        $this->container['transfer_note2'] = $transfer_note2;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


