<?php
/**
 * Product
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.13
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace kruegge82\DHL\Model;
use \kruegge82\DHL\ObjectSerializer;

/**
 * Product Class Doc Comment
 *
 * @category Class
 * @description Determines the DHL Paket product to be used.  * V01PAK: DHL PAKET; * V53WPAK: DHL PAKET International; * V54EPAK: DHL Europaket; * V62WP: Warenpost (will be replaced by DHL Kleinpaket from 1.1.2025); * V62KP: DHL Kleinpaket; * V66WPI: Warenpost International
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Product
{
    /**
     * Possible values of this enum
     */
    public const V01_PAK = 'V01PAK';

    public const V53_WPAK = 'V53WPAK';

    public const V54_EPAK = 'V54EPAK';

    public const V62_WP = 'V62WP';

    public const V62_KP = 'V62KP';

    public const V66_WPI = 'V66WPI';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::V01_PAK,
            self::V53_WPAK,
            self::V54_EPAK,
            self::V62_WP,
            self::V62_KP,
            self::V66_WPI
        ];
    }
}


