<?php
/**
 * ValidationMessageItemTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  kruegge82\DHL
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Parcel DE Shipping API (Post & Parcel Germany)
 *
 * Note: This is the specification of the DPDHL Group Parcel DE Shipping API for Post & Parcel Germany. This REST web service allows business customers to create shipping labels on demand.
 *
 * The version of the OpenAPI document: 2.1.10
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace kruegge82\DHL\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ValidationMessageItemTest Class Doc Comment
 *
 * @category    Class
 * @description Representation of a validation message of a shipment container containing the most important information.
 * @package     kruegge82\DHL
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ValidationMessageItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ValidationMessageItem"
     */
    public function testValidationMessageItem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "property"
     */
    public function testPropertyProperty()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validation_message"
     */
    public function testPropertyValidationMessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "validation_state"
     */
    public function testPropertyValidationState()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
